spring.application.name=stock-trading-platform

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/trading_db
spring.datasource.username=postgres
spring.datasource.password=Prakash@b17

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS=false

jwt.secret=mySecretKeyForTradingPlatform
jwt.expiration=86400000